language: go
go:
- 1.12.x
services:
- docker
env:
- GO111MODULE="on"

before_install:
- GO111MODULE="off" go get github.com/mattn/goveralls

install:
- go mod download

script:
- go test -v -cover -coverprofile=coverage.out 
- $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci

after_success:
- test -n "$TRAVIS_TAG" && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
